let startOfYesterday = startofday(datetime_utc_to_local(now(), "Europe/London") - 1d);
let startOfToday = startofday(datetime_utc_to_local(now(), "Europe/London"));
let startOfYesterdayUtc = datetime_local_to_utc(startOfYesterday, "Europe/London");
let startOfTodayUtc = datetime_local_to_utc(startOfToday, "Europe/London");
customEvents
| where timestamp >= startOfYesterdayUtc and timestamp < startOfTodayUtc
| where cloud_RoleName == "hmpps-probation-supervision-appointments-api"
| summarize Count = count() by Event = name
| order by Count desc