---
# Per environment values which override defaults in hmpps-probation-supervision-appointments-api/values.yaml

generic-service:
  replicaCount: 2
  ingress:
    host: probation-supervision-appointments-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-NAME-DATE: "f8b05ebb-4c99-4906-a8e2-4433a550041f"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-NAME-DATE-LOCATION: "e700a64b-e8dd-4e4d-ba68-bbc58c45618e"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH-WITH-NAME-DATE: "44a1728f-a145-4b3d-8877-6a34ce0fbb04"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH_WITH-WITH-NAME-DATE-LOCATION: "8deacf0e-b884-4e1b-bf48-b44d11285249"
    SENTRY_ENVIRONMENT: prod
    OUTLOOK_ENVIRONMENT: prod
    SERVICES_SUPERVISION-API_BASE-URL: 'https://probation-supervision-appointments-api.hmpps.service.justice.gov.uk'
# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: manage-people-on-probation-prod
