---
# Per environment values which override defaults in hmpps-probation-supervision-appointments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-supervision-appointments-api-preprod.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-NAME-DATE: "d4431224-85c9-4fec-8929-d703212d38f8"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-NAME-DATE-LOCATION: "979038da-6ee5-445d-9ff2-cc3ede540d68"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH-WITH-NAME-DATE: "7542e497-c13a-4a1d-a287-434684dfee8e"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH_WITH-WITH-NAME-DATE-LOCATION: "2d007925-f7e9-42dd-9a5a-2115a340ffdc"
    SENTRY_ENVIRONMENT: preprod
    OUTLOOK_ENVIRONMENT: preprod
    SERVICES_SUPERVISION-API_BASE-URL: 'https://probation-supervision-appointments-api-preprod.hmpps.service.justice.gov.uk'

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: manage-people-on-probation-preprod
