---
# Per environment values which override defaults in hmpps-probation-supervision-appointments-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: probation-supervision-appointments-api-preprod.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in-preprod.hmpps.service.justice.gov.uk/auth"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITH-APPOINTMENT-TYPE: "20293306-6dd1-482c-b0be-ba0f8e5b3dc8"
    GOVUK-NOTIFY_TEMPLATEIDS_ENGLISH-WITHOUT-APPOINTMENT-TYPE: "03a6fbc3-e413-400c-b001-fcef8cc268e2"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH-WITH-APPOINTMENT-TYPE: "9a234c0f-cdaf-4058-8b47-c7c1d56c3373"
    GOVUK-NOTIFY_TEMPLATEIDS_WELSH-WITHOUT-APPOINTMENT-TYPE: "d39ca069-02a9-45f7-9526-4b9184516f91"
    SENTRY_ENVIRONMENT: preprod
    OUTLOOK_ENVIRONMENT: preprod
    SERVICES_SUPERVISION-API_BASE-URL: 'https://probation-supervision-appointments-api-preprod.hmpps.service.justice.gov.uk'

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: manage-people-on-probation-preprod
