CREATE TABLE  delius_outlook_mappings
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delius_external_reference TEXT        NOT NULL,
    outlook_id                TEXT        NOT NULL,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_delius_ref_not_blank CHECK (length(trim(delius_external_reference)) > 0),
    CONSTRAINT chk_outlook_id_not_blank CHECK (length(trim(outlook_id)) > 0),
    CONSTRAINT uq_delius_outlook_pair UNIQUE (delius_external_reference, outlook_id)
);

CREATE INDEX idx_delius_outlook__delius_ref
    ON delius_outlook_mappings (delius_external_reference);

CREATE INDEX idx_delius_outlook__outlook_id
    ON delius_outlook_mappings (outlook_id);
