
CREATE TABLE notification_mappings
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delius_external_reference TEXT        NOT NULL,
    notificationId            UUID        NOT NULL,
    templateId            UUID        NOT NULL,
    message                   TEXT        NOT NULL,
    created_at                TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);